#!/bin/bash
exec 2>&1
exec /sbin/setuser nobody Xvnc4 :1 -geometry 1280x800 -depth 16 -rfbwait 30000 -SecurityTypes None -rfbport 5901 -bs -ac \
				   -pn -fp /usr/share/fonts/X11/misc/,/usr/share/fonts/X11/75dpi/,/usr/share/fonts/X11/100dpi/ \
				   -co /etc/X11/rgb -dpi 96
